trigger:
- release/rocm-rel-6.0

pool: gfx1100
steps:
- script: mkdir build
  displayName: 'Making Build directory'

- script: ./install -c
  displayName: 'Building hipCUB using install script'

- script: |
    cd build
    ls 
    cd release
    ctest
  displayName: 'Running tests'

